import './assign/index.js'
// import './assign-concat/index.js'
// import './compand/index.js'
// import './decompand/index.js'
// import './define-properties/index.js'
// import './expand/index.js'
// import './freeze/index.js'
// import './get-property/index.js'
// import './get-own-property-descriptors/index.js'
// import './impand/index.js'
// import './is-array-like/index.js'
// import './seal/index.js'
// import './set-property/index.js'
// import './split-path/index.js'
// import './to-string/index.js'
// import './type-of/index.js'
// import './value-of/index.js'
// import './readme.md/index.js'
