// import './compand/index.js'
// import './decompand/index.js'
// import './expand/index.js'
// import './impand/index.js'
// import './get-own-property-descriptors/index.js'
// import './define-properties/index.js'
// import './type-of/index.js'
// import './is-array-like/index.js'
// import './seal/index.js'
// import './freeze/index.js'
// import './assign/index.js'
// import './assign-concat/index.js'
import './set-property/index.js'
